name: "Hola mundo"

on:
  push:
    branches: [ main ]

jobs:
  deploy-prueba:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout del código"
        uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigo"
      - run: echo "Corrre migraciones"
      - run: echo "Genera binario"
      - run: echo "Public version"

    
    
